FROM alpine:latest

ENV GOKINS_WORKPATH=/data/gokins

RUN apk update \
    && apk --no-cache add openssl ca-certificates curl git wget \
    && rm -rf /var/cache/apk \
    && mkdir -p /data/gokins

COPY bin/gokins-alpine /usr/bin/gokins
WORKDIR /data
ENTRYPOINT ["/usr/bin/gokins"]
